config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "index#index"

  get 'sitemap' => 'sitemap#show', format: 'xml'
  match 'robots.txt' => 'robots_txt#index'

  scope 'admin' do
    match '/' => "admin#index"

    resources :categories, :counters, :pages, :text_zones

    resources :item_order do
      collection do
        put '/' => 'item_order#update'
      end
    end


    resources :file_management do
      collection do
        get :images, format: 'json'
        get :attachments, format: 'json'
      end

      collection do
        match :picture_upload
        match :attachment_upload
      end
    end

    resources :news do
      collection do
        get '/' => "news#admin_index"
      end
    end

    resources :orders do
      collection do
        get 'settings' => 'orders#settings', :as => :settings
        post 'settings' => 'orders#update_settings'
        put 'settings' => 'orders#update_settings'
        get 'resend/:id' => 'orders#resend', :as => :resend
      end
    end
  end

  match 'users/sign_up', to: redirect('/')

  devise_for :users, {
      class_name: User,
      module: :devise,
  }

  prefix = Rails.application.routes.catalog_prefix if Rails.application.routes.respond_to?(:catalog_prefix)

  if prefix.present?
    prefix = prefix.prepend('/') unless prefix[0] == '/'
    get prefix => 'catalog#index', as: :catalog
  else
    get '/catalog' => 'catalog#index', as: :catalog
  end

  # TODO enable domain-specific categories here
  get "#{prefix}/(*slug)" => 'catalog#show', :as => :show_category, :constraints => lambda { |req|
    if !req.path.starts_with?('/admin')
      Category.where(slug: req.params[:slug]).exists?
    else
      false
    end
  }

  subdomains_enabled = false # Rails.application.config.subdomains_enabled
  match "/(*slug)" => 'pages#show', :as => :show_page, :constraints => lambda { |req|
    criteria = Page.where(slug: req.params[:slug])

    if subdomains_enabled
      req.params[:subdomain] = req.subdomain == 'www' ? ['www', ''] : [req.subdomain]
      criteria = criteria.in(subdomain: req.params[:subdomain])
    end

    criteria.exists?
  }

end

app/views/admin/index.html.haml
.row
  .span6
    %h1 Контент

    %h2= link_to 'Каталог', categories_path
    %p Страницы каталога товаров и услуг.

    %h2= link_to 'Страницы', pages_path
    %p Прочие страницы сайта, например, информация о контактах, вакансиях и так далее.

    %h2= link_to 'Новости', '/admin/news'
    %p Новости компании

    %h2= link_to 'Файлы', file_management_index_path
    %p Картинки и файлы, загруженные с помощью визуального редактора.

    %h2= link_to 'Текстовые зоны', text_zones_path
    %p Расположены на страницах сайта, но не относятся непоследственно к контенту. Текст в подвале, содержимое robots.txt и так далее.

    != render partial: 'custom_content'
  .span6
    %h1 Пользовательские данные
    - if respond_to? :orders_path
      %h2= link_to 'Заказы', orders_path
      %p Информация о заказах, размещенных через сайт.

    != render partial: 'custom_user_content'
  .span6
    %h1 Настройки
    %h2= link_to 'Счетчики', counters_path
    %p Устанавливаются в подвале сайта и позволяют следить за статистикой посещаемости.

    %h2= link_to 'Настройки почты', settings_orders_path
    %p Почтовые адреса для каждого отдела компании

    != render partial: 'custom_settings'