config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "index#index"

  get 'sitemap' => 'sitemap#show', format: 'xml'
  match 'robots.txt' => 'robots_txt#index'

  scope 'admin' do
    match '/' => "admin#index"

    resources :categories, :counters, :pages, :text_zones

    resources :item_order do
      collection do
        put '/' => 'item_order#update'
      end
    end


    resources :file_management do
      collection do
        get :images, format: 'json'
        get :attachments, format: 'json'
      end

      collection do
        match :picture_upload
        match :attachment_upload
      end
    end

    resources :news do
      collection do
        get '/' => "news#admin_index"
      end
    end

    resources :orders do
      collection do
        get 'settings' => 'orders#settings', :as => :settings
        post 'settings' => 'orders#update_settings'
        put 'settings' => 'orders#update_settings'
        get 'resend/:id' => 'orders#resend', :as => :resend
      end
    end
  end

  match 'users/sign_up', to: redirect('/')

  devise_for :users, {
      class_name: User,
      module: :devise,
  }

  prefix = Rails.application.routes.catalog_prefix if Rails.application.routes.respond_to?(:catalog_prefix)

  if prefix.present?
    prefix = prefix.prepend('/') unless prefix[0] == '/'
    get prefix => 'catalog#index', as: :catalog
  else
    get '/catalog' => 'catalog#index', as: :catalog
  end

  # TODO enable domain-specific categories here
  get "#{prefix}/(*slug)" => 'catalog#show', :as => :show_category, :constraints => lambda { |req|
    if !req.path.starts_with?('/admin')
      Category.where(slug: req.params[:slug]).exists?
    else
      false
    end
  }

  subdomains_enabled = false # Rails.application.config.subdomains_enabled
  match "/(*slug)" => 'pages#show', :as => :show_page, :constraints => lambda { |req|
    criteria = Page.where(slug: req.params[:slug])

    if subdomains_enabled
      req.params[:subdomain] = req.subdomain == 'www' ? ['www', ''] : [req.subdomain]
      criteria = criteria.in(subdomain: req.params[:subdomain])
    end

    criteria.exists?
  }

end

app/views/shared/_benefits.html.haml
%h2 Наши преимущества
%ul
  %li
    помимо алюминиевых полуфабрикатов компания имеет большой ассортимент медного, латунного, бронзового, черного, нержавеющего и инструментального металлопроката
  %li
    предлагаемый нами из складского наличия ассортимент металлопроката является одним из крупнейших в регионе
  %li
    предложение наиболее выгодных цен
  %li
    наличие металлопроката высокого качества с возможностью прохождения аттестации ФГУП «АВИАТЕХПРИЕМКА»
  %li
    комплекс сервисных услуг по резке
  %li
    доставка металлопроката по всей Российской Федерации
  %li
    Кроме этого имеем возможность изготовления по заводской цене профилей по Вашим чертежам

app/views/shared/_breadcrumbs.html.haml
%ul.breadcrumb
  %li 
    %a{:href => '/'} Главная
    %span.divider /
  - (@path[0, @path.size - 1] || []).each_with_index do |item, index|
    %li
      - url = controller_name == "pages" ? @path_translit[index] : show_category_path(@path_translit[index])
      %a{:href => url}= item
      %span.divider /
  %li.active= @path.last

app/views/shared/_meta_form.html.haml
:css
  .meta-controls {
    display: none;
  }

.control-group.meta-edit
  .controls
    %a.btn.btn-primary
      %i.icon-edit.icon-white
      Редактировать мета-тэги

  :javascript
    $('.meta-edit a').click(function () { $('.meta-controls').show() && $('.meta-edit').hide(); });
.meta-controls
  = f.fields_for :meta do |meta_form|
    - %w'title keywords description'.each do |field|
      .control-group
        = meta_form.label field, field.capitalize, :class => 'control-label'
        .controls
          = meta_form.text_field field, :class => 'span12', :value => (object.meta[field] rescue nil)

app/views/shared/_navigation.html.haml
- if user_signed_in?
  %li
    = link_to('Logout', destroy_user_session_path, :method=>'delete')
- else
  %li
    = link_to('Login', new_user_session_path)
- if user_signed_in?
  %li
    = link_to('Edit account', edit_user_registration_path)
- else
  %li
    = link_to('Sign up', new_user_registration_path)

app/views/shared/_news_nav.html.haml
.well
  %p
    .btn-group
      %a.btn.btn-primary{href: new_news_path}
        %i.icon-edit.icon-white
        Добавить новость

  %h3
    Новости
  %ul.nav.nav-list
    - News.only(:id, :name, :created_at, :real_date).all.each do |news|
      %li{:class => defined?(@news) && news.id == @news.id ? 'active' : ''}
        %a{:href => edit_news_path(news)}!= news.name

app/views/shared/_pages_nav.html.haml
.well
  %p
    .btn-group
      %a.btn.btn-primary{href: new_page_path}
        %i.icon-white.icon-edit
        Добавить страницу

  %h3
    Страницы

  %ul.nav.nav-list
    - Page.first_level.only(:id, :name).asc(:path).each do |page|
      %li.nav-header{:class => defined?(@page) && page.id == @page.id ? 'active' : ''}
        %a{:href => edit_page_path(page)}!= page.name

        = render partial: 'shared/recursive_page_nav_list', locals: {page: page}

app/views/shared/_path.html.haml
.control-group
  = f.label :name_translit, "Путь", :class => 'control-label'
  .controls
    = f.text_field :name_translit, :class => 'span12', placeholder: 'Если не заполнено, то заполняется автоматически'
- if f.object.respond_to?(:subdomain) && f.object.kind_of?(Page)
  .control-group
    = f.label :subdomain, "Поддомен", :class => 'control-label'
    .controls
      = f.text_field :subdomain, :class => 'span12', placeholder: 'Лучше не трогать'

app/views/shared/_product_index.html.haml
.row-fluid
  .span4
    = render 'shared/product_nav'  
  .span8

app/views/shared/_product_nav.html.haml
.well
  %p
    .btn-group
      %a.btn.btn-primary{href: new_category_path}
        %i.icon-edit.icon-white
        Добавить категорию
      %a.btn.btn-primary.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
        %span.caret

  %h3 Все категории

  %select.chzn-select#category-select(data-placeholder="Выберите категорию..." style="width: 100%;")
    %option(value="")
    - Category.includes(:name, :id).each do |c|
      %option(value="#{c.id}")= c.name

  :javascript
    $('#category-select').chosen().change(function() {
      var value = $(this).find(':selected').attr('value');
      document.location.assign("#{edit_category_path('path')}".replace('path', value));
    });

  - if @category.present? && (children = (parent = @category.parent).present? ? parent.children : Category.first_level) && children.any?
    %h3
      Соседи
      %small
        (#{link_to 'наверх', (parent.present? ? edit_item_order_path(parent) : item_order_index_path)})

    %ul.unstyled
      - children.only(:id, :name).each do |category|
        %li
          %a(title='Раскрыть' href="#{(has_children = category.children.any?) ? edit_item_order_path(category) : '#'}")
            %i(class="#{has_children ? 'icon-plus' : 'icon-white'}")
          = link_to category.name, edit_category_path(category)

app/views/shared/_recursive_page_nav_list.html.haml
- (page.children || []).each do |subpage|
  %li{:class => "nav-content-#{subpage.id}", style: "padding-left: 20px;"}
    %a{:href => edit_page_path(subpage), style: defined?(@page) && subpage.id == @page.id ? 'text-decoration: underline' : ''}!= subpage.name
    - if subpage.respond_to?(:children) && subpage.children.present?
      %ul.unstyled
        = render partial: 'shared/recursive_page_nav_list', locals: {page: subpage}

app/views/shared/_recursive_product_nav_list.html.haml
%li.nav-content{'data-item-id' => item.id, style: "padding-left: 18px;"}
  - if item.respond_to?(:children)
    - if (children = item.children).present?
      %a.toggle_category{href: "#", style: 'display: inline;'}
        %b.icon-minus-sign &nbsp;
    - else
      %b.icon-white &nbsp;
    %a{:href => edit_category_path(item), class: defined?(@item) && item.id == @item.id ? 'active' : ''}!= item.name
    - if children.present?
      %ul.unstyled
        - children.each do |item|
          = render partial: 'shared/recursive_product_nav_list', locals: {item: item}
  - else
    %b.icon-white &nbsp;
    %a{:href => edit_product_path(item), style: defined?(@product) && item.id == @product.id ? 'text-decoration: underline' : ''}!= item.name

app/views/shared/_teaser_form.html.haml
.control-group
  = f.label :teaser, "Короткое описание", :class => 'control-label'
  .controls
    = f.text_area :teaser, :class => 'span5', :placeholder => 'Показывается на страницах каталога и в сниппетах', :rows => 2
.control-group
  = f.label :teaser_picture_link, "Ссылка на картинку для описания", :class => 'control-label'
  .controls
    = f.text_field :teaser_picture_link, :class => 'span6'
    = f.file_field :teaser_picture

app/views/shared/_yandex_share.html.haml
:plain
  <script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
  <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="none" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj,moikrug,gplus"></div>