config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "index#index"

  get 'sitemap' => 'sitemap#show', format: 'xml'
  match 'robots.txt' => 'robots_txt#index'

  scope 'admin' do
    match '/' => "admin#index"

    resources :categories, :counters, :pages, :text_zones

    resources :item_order do
      collection do
        put '/' => 'item_order#update'
      end
    end


    resources :file_management do
      collection do
        get :images, format: 'json'
        get :attachments, format: 'json'
      end

      collection do
        match :picture_upload
        match :attachment_upload
      end
    end

    resources :news do
      collection do
        get '/' => "news#admin_index"
      end
    end

    resources :orders do
      collection do
        get 'settings' => 'orders#settings', :as => :settings
        post 'settings' => 'orders#update_settings'
        put 'settings' => 'orders#update_settings'
        get 'resend/:id' => 'orders#resend', :as => :resend
      end
    end
  end

  match 'users/sign_up', to: redirect('/')

  devise_for :users, {
      class_name: User,
      module: :devise,
  }

  prefix = Rails.application.routes.catalog_prefix if Rails.application.routes.respond_to?(:catalog_prefix)

  if prefix.present?
    prefix = prefix.prepend('/') unless prefix[0] == '/'
    get prefix => 'catalog#index', as: :catalog
  else
    get '/catalog' => 'catalog#index', as: :catalog
  end

  # TODO enable domain-specific categories here
  get "#{prefix}/(*slug)" => 'catalog#show', :as => :show_category, :constraints => lambda { |req|
    if !req.path.starts_with?('/admin')
      Category.where(slug: req.params[:slug]).exists?
    else
      false
    end
  }

  subdomains_enabled = false # Rails.application.config.subdomains_enabled
  match "/(*slug)" => 'pages#show', :as => :show_page, :constraints => lambda { |req|
    criteria = Page.where(slug: req.params[:slug])

    if subdomains_enabled
      req.params[:subdomain] = req.subdomain == 'www' ? ['www', ''] : [req.subdomain]
      criteria = criteria.in(subdomain: req.params[:subdomain])
    end

    criteria.exists?
  }

end

app/models/category.rb
# coding: utf-8
class Category
  include Mongoid::Document
  include Extensions::Translit
  include Extensions::Meta
  include Extensions::OrderByInteger
  include Extensions::Cleanup
  include Extensions::Path
  #include Extensions::UpdateRoutes
  include Extensions::Teaser

  field :description
  cleanup_markup_for :description

  field :features, type: Array, default: []

  mount_uploader :picture, CategoryPictureUploader

  belongs_to :category
  scope :first_level, where(category_id: nil)

  has_many :categories

  alias_method :parent, :category
  alias_method :children, :categories

  def destroy
    if (children || []).size.zero?
      super
    else
      errors.add :base, "Невозможно удалить категорию, потому что у нее есть дети"
      false
    end
  end

  alias_method :old_breadcrumbs, :breadcrumbs

  def breadcrumbs
    old = old_breadcrumbs
    old.pop

    old << old_breadcrumbs.last.collect do |str|
      str.sub '/', ''
    end

    old
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    redirect_to item_order_index_path
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to edit_category_path(@category), notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to edit_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url }
        format.json { head :no_content }
      end
    else
      render action: "edit"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category, :html => {:class => 'form-horizontal'} do |f|
  -if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    = render 'shared/meta_form', :object => @category, :f => f
    .control-group
      = f.label :name, "Имя", :class => 'control-label'
      .controls
        = f.text_field :name, :class => 'span12'

    = render 'shared/path', :object => @category, :f => f

    .control-group
      = f.label :category_id, "Родительская категория", :class => 'control-label'
      .controls
        = f.select(:category_id, options_from_collection_for_select(Category.unscoped.not_in(_id: [@category.id]).asc(:name).to_a, :id, :name, @category.category_id), {include_blank: ''}, class: 'span12 chzn-select', "data-placeholder" => 'Выберите категорию')

    .control-group
      = f.label :teaser, 'Краткое описание', class: 'control-label'
      .controls
        = f.text_area :teaser, class: 'span12', rows: 2

    .control-group
      = f.label :picture, 'Картинка', class: 'control-label'
      .controls
        - if @category.picture.present?
          %img.img-rounded.bordered.pull-left{src: @category.picture.thumb.url}
          .pull-left.offset1
            = f.label :remove_picture, 'Удалить', {class: 'checkbox'} do
              Удалить
              = f.check_box :remove_picture
            %br
            = f.file_field :picture
        - else
          = f.file_field :picture

    = f.cktext_area :description

    .control-group
      = f.label :enable_cleanup, "Очистить разметку", :class => 'control-label'
      .controls
        = f.check_box :enable_cleanup

  .form-actions
    = f.submit 'Сохранить', :class => 'btn btn-primary'
    - if @category.persisted?
      = link_to 'Показать на сайте', show_category_url(@category.slug), :class => 'btn btn-success', :target => 'blank'
      = link_to 'Удалить', @category, :confirm => 'Точно хотите УДАЛИТЬ?', :method => :delete, :class => 'btn btn-danger'

:css
  .bordered {
    border: 1px solid black;
  }

app/views/categories/edit.html.haml
.row-fluid
  .span4
    = render 'shared/product_nav'
  .span8
    = render partial: 'item_order/breadcrumbs'
    %h1 #{@category.name}

    = render 'form'

app/views/categories/index.html.haml
= render 'shared/product_index'

app/views/categories/new.html.haml
.row-fluid
  .span4
    = render 'shared/product_nav'  
  .span8
    %h1 Добавить категорию

    = render 'form'

app/views/categories/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path