config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "index#index"

  get 'sitemap' => 'sitemap#show', format: 'xml'
  match 'robots.txt' => 'robots_txt#index'

  scope 'admin' do
    match '/' => "admin#index"

    resources :categories, :counters, :pages, :text_zones

    resources :item_order do
      collection do
        put '/' => 'item_order#update'
      end
    end


    resources :file_management do
      collection do
        get :images, format: 'json'
        get :attachments, format: 'json'
      end

      collection do
        match :picture_upload
        match :attachment_upload
      end
    end

    resources :news do
      collection do
        get '/' => "news#admin_index"
      end
    end

    resources :orders do
      collection do
        get 'settings' => 'orders#settings', :as => :settings
        post 'settings' => 'orders#update_settings'
        put 'settings' => 'orders#update_settings'
        get 'resend/:id' => 'orders#resend', :as => :resend
      end
    end
  end

  match 'users/sign_up', to: redirect('/')

  devise_for :users, {
      class_name: User,
      module: :devise,
  }

  prefix = Rails.application.routes.catalog_prefix if Rails.application.routes.respond_to?(:catalog_prefix)

  if prefix.present?
    prefix = prefix.prepend('/') unless prefix[0] == '/'
    get prefix => 'catalog#index', as: :catalog
  else
    get '/catalog' => 'catalog#index', as: :catalog
  end

  # TODO enable domain-specific categories here
  get "#{prefix}/(*slug)" => 'catalog#show', :as => :show_category, :constraints => lambda { |req|
    if !req.path.starts_with?('/admin')
      Category.where(slug: req.params[:slug]).exists?
    else
      false
    end
  }

  subdomains_enabled = false # Rails.application.config.subdomains_enabled
  match "/(*slug)" => 'pages#show', :as => :show_page, :constraints => lambda { |req|
    criteria = Page.where(slug: req.params[:slug])

    if subdomains_enabled
      req.params[:subdomain] = req.subdomain == 'www' ? ['www', ''] : [req.subdomain]
      criteria = criteria.in(subdomain: req.params[:subdomain])
    end

    criteria.exists?
  }

end

app/models/text_zone.rb
class TextZone
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :enabled, :type => Boolean, default: true
  field :source, :type => String

  validates_uniqueness_of :name

  scope :public, where(enabled: true)
end

app/controllers/text_zones_controller.rb
class TextZonesController < ApplicationController
  before_filter :authenticate_user!

  # GET /text_zones
  # GET /text_zones.json
  def index
    @text_zones = TextZone.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @text_zones }
    end
  end

  # GET /text_zones/1
  # GET /text_zones/1.json
  def show
    @text_zone = TextZone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text_zone }
    end
  end

  # GET /text_zones/new
  # GET /text_zones/new.json
  def new
    @text_zone = TextZone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @text_zone }
    end
  end

  # GET /text_zones/1/edit
  def edit
    @text_zone = TextZone.find(params[:id])
  end

  # POST /text_zones
  # POST /text_zones.json
  def create
    @text_zone = TextZone.new(params[:text_zone])

    respond_to do |format|
      if @text_zone.save
        format.html { redirect_to text_zones_url, notice: 'Text zone was successfully created.' }
        format.json { render json: @text_zone, status: :created, location: @text_zone }
      else
        format.html { render action: "new" }
        format.json { render json: @text_zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /text_zones/1
  # PUT /text_zones/1.json
  def update
    @text_zone = TextZone.find(params[:id])

    respond_to do |format|
      if @text_zone.update_attributes(params[:text_zone])
        format.html { redirect_to text_zones_url, notice: 'Text zone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @text_zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_zones/1
  # DELETE /text_zones/1.json
  def destroy
    @text_zone = TextZone.find(params[:id])
    @text_zone.destroy

    respond_to do |format|
      format.html { redirect_to text_zones_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/text_zones_helper.rb
module TextZonesHelper
end

app/views/text_zones/_form.html.haml
= form_for @text_zone, html: {class: 'form-horizontal'} do |f|
  -if @text_zone.errors.any?
    .alert.alert-error#error_explanation
      %h2= "Внезапно, ошибка!"
      %ul
        - @text_zone.errors.full_messages.each do |msg|
          %li= msg
  %fieldset
    .control-group
      = f.label :name, 'Имя', class: 'control-label'
      .controls
        = f.text_field :name, class: 'span6', placeholder: 'Например, footer'

    .control-group
      = f.label :description, 'Описание', class: 'control-label'
      .controls
        = f.text_area :description, class: 'span6', rows: 3, placeholder: 'Например, "для отображения в самом низу страницы"'

    .control-group
      = f.label :enabled, 'Показывать?', class: 'control-label'
      .controls
        = f.check_box :enabled
    .control-group
      = f.label :source, 'Текст', class: 'control-label'
      .controls
        = f.text_area :source, class: 'span6', rows: 25, placeholder: 'Например, "наш адрес - улица Такая-то, дом 1"'

  .form-actions
    = f.submit "Обновить", class: 'btn btn-primary'
    = link_to "Отменить", :back, class: 'btn btn-secondary'
    = link_to "Удалить", text_zone_path, :confirm => "Вы уверены, что хотите УДАЛИТЬ учетную запись?", :method => :delete, class: 'btn btn-danger' if @text_zone.persisted?

app/views/text_zones/edit.html.haml
%h1 Редактирование текстовой зоны #{@text_zone.name}

= render 'form'

app/views/text_zones/index.html.haml
%h1 Текстовые зоны

%table.table.table-bordered.table-striped
  %tr
    %th Название
    %th.span2 Отображается
    %th Описание
    %th.span1

  - @text_zones.each do |text_zone|
    %tr
      %td= link_to text_zone.name, edit_text_zone_path(text_zone)
      %td= text_zone.enabled ? 'да' : 'нет'
      %td= text_zone.description
      %td
        = link_to 'Удалить', text_zone, :class => 'btn btn-danger', :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'Добавить текстовую зону', new_text_zone_path, :class => 'btn btn-primary'

app/views/text_zones/new.html.haml
%h1 Создание текстовой зоны

= render 'form'

app/views/text_zones/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @text_zone.name
%p
  %b Enabled:
  = @text_zone.enabled
%p
  %b Source:
  = @text_zone.source

= link_to 'Edit', edit_text_zone_path(@text_zone)
\|
= link_to 'Back', text_zones_path